// Static bracket wiring config for all 8 events.
// Source of truth for downstream slot resolution on match completion.
// E1 R1 losers, BLP loser, and consolation pool assignments are NOT wired here —
// those are dynamic and handled by fire_blp / generate_consolation_pools RPCs.

export type SourceResult = 'winner' | 'loser';

export type TargetSlot = 'p1' | 'p2';

export interface WiringRule {
  source: string;
  sourceResult: SourceResult;
  target: string;
  targetSlot: TargetSlot;
}

export interface EventWiring {
  eventCode: string;
  wiring: WiringRule[];
}

// ─────────────────────────────────────────────────────────────────────────────
// E1 — U11 Boys Singles
// 14 R1 players (7 matches) → 7 winners + BLP winner = 8 QF entrants.
// R1 losers feed BLP eligibility / consolation pools dynamically (RPC-driven).
// ─────────────────────────────────────────────────────────────────────────────

const E1_WIRING: WiringRule[] = [
  // R1 winners → QF
  { source: 'R1.1', sourceResult: 'winner', target: 'QF1', targetSlot: 'p1' },
  { source: 'R1.2', sourceResult: 'winner', target: 'QF1', targetSlot: 'p2' },
  { source: 'R1.3', sourceResult: 'winner', target: 'QF2', targetSlot: 'p1' },
  { source: 'R1.4', sourceResult: 'winner', target: 'QF2', targetSlot: 'p2' },
  { source: 'R1.5', sourceResult: 'winner', target: 'QF3', targetSlot: 'p1' },
  { source: 'R1.6', sourceResult: 'winner', target: 'QF3', targetSlot: 'p2' },
  { source: 'R1.7', sourceResult: 'winner', target: 'QF4', targetSlot: 'p1' },
  // BLP winner fills the 8th QF slot
  { source: 'BLP', sourceResult: 'winner', target: 'QF4', targetSlot: 'p2' },
  // QF → SF
  { source: 'QF1', sourceResult: 'winner', target: 'SF1', targetSlot: 'p1' },
  { source: 'QF2', sourceResult: 'winner', target: 'SF1', targetSlot: 'p2' },
  { source: 'QF3', sourceResult: 'winner', target: 'SF2', targetSlot: 'p1' },
  { source: 'QF4', sourceResult: 'winner', target: 'SF2', targetSlot: 'p2' },
  // SF → F
  { source: 'SF1', sourceResult: 'winner', target: 'F', targetSlot: 'p1' },
  { source: 'SF2', sourceResult: 'winner', target: 'F', targetSlot: 'p2' },
  // SF losers → 3rd place
  { source: 'SF1', sourceResult: 'loser', target: '3P', targetSlot: 'p1' },
  { source: 'SF2', sourceResult: 'loser', target: '3P', targetSlot: 'p2' },
];

// ─────────────────────────────────────────────────────────────────────────────
// Standard 6-player bracket (E2, E3, E4, E5, E7)
// 3 R1 matches + 1 T1 bye → 2 SF → F + 3P + 3-player ConRR pool + ConF.
// T1 occupies SF1.p1 by static seed (no wiring rule — seeded directly).
// R1 losers each appear in 2 ConRR matches (every pair plays each other once).
// ConRR ordering: ConRR.1 = R1.2L vs R1.3L, ConRR.2 = R1.1L vs R1.2L, ConRR.3 = R1.1L vs R1.3L
// ConF is filled by complete_match RPC after all 3 ConRR matches finish.
// ─────────────────────────────────────────────────────────────────────────────

const STANDARD_BRACKET_WIRING: WiringRule[] = [
  // R1 winners → SF.
  // SF1.p1 is occupied by the bye holder (T1/P1) at seed time — no wiring rule needed for it.
  // R1.1 winner fills SF1.p2; R1.2 and R1.3 winners fill SF2.
  { source: 'R1.1', sourceResult: 'winner', target: 'SF1', targetSlot: 'p2' },
  { source: 'R1.2', sourceResult: 'winner', target: 'SF2', targetSlot: 'p1' },
  { source: 'R1.3', sourceResult: 'winner', target: 'SF2', targetSlot: 'p2' },
  // R1 losers → ConRR matches (each loser appears in 2 matches)
  { source: 'R1.1', sourceResult: 'loser', target: 'ConRR.2', targetSlot: 'p1' },
  { source: 'R1.1', sourceResult: 'loser', target: 'ConRR.3', targetSlot: 'p1' },
  { source: 'R1.2', sourceResult: 'loser', target: 'ConRR.1', targetSlot: 'p1' },
  { source: 'R1.2', sourceResult: 'loser', target: 'ConRR.2', targetSlot: 'p2' },
  { source: 'R1.3', sourceResult: 'loser', target: 'ConRR.1', targetSlot: 'p2' },
  { source: 'R1.3', sourceResult: 'loser', target: 'ConRR.3', targetSlot: 'p2' },
  // SF → F
  { source: 'SF1', sourceResult: 'winner', target: 'F', targetSlot: 'p1' },
  { source: 'SF2', sourceResult: 'winner', target: 'F', targetSlot: 'p2' },
  // SF losers → 3rd place
  { source: 'SF1', sourceResult: 'loser', target: '3P', targetSlot: 'p1' },
  { source: 'SF2', sourceResult: 'loser', target: '3P', targetSlot: 'p2' },
];

// ─────────────────────────────────────────────────────────────────────────────
// All-event registry
// E6 and E8 are pure round-robin events — no progression wiring.
// E6 matches are pre-seeded; E8 matches are generated by lock_e8_draw RPC.
// ─────────────────────────────────────────────────────────────────────────────

export const BRACKET_WIRING: Record<string, EventWiring> = {
  E1: { eventCode: 'E1', wiring: E1_WIRING },
  E2: { eventCode: 'E2', wiring: STANDARD_BRACKET_WIRING },
  E3: { eventCode: 'E3', wiring: STANDARD_BRACKET_WIRING },
  E4: { eventCode: 'E4', wiring: STANDARD_BRACKET_WIRING },
  E5: { eventCode: 'E5', wiring: STANDARD_BRACKET_WIRING },
  E6: { eventCode: 'E6', wiring: [] },
  E7: { eventCode: 'E7', wiring: STANDARD_BRACKET_WIRING },
  E8: { eventCode: 'E8', wiring: [] },
};

// ─────────────────────────────────────────────────────────────────────────────
// Helper: getDownstreamSlots
//
// Given a completed match's event + bracket_slot + result (winner/loser),
// return all wiring rules that depend on that result.
// Client passes these to complete_match RPC's downstream_updates parameter.
//
// `result` is 'winner' or 'loser' — the two outcomes a match completion produces.
// ─────────────────────────────────────────────────────────────────────────────

export function getDownstreamSlots(
  eventCode: string,
  bracketSlot: string,
  result: 'winner' | 'loser',
): WiringRule[] {
  const eventWiring = BRACKET_WIRING[eventCode];
  if (!eventWiring) return [];
  return eventWiring.wiring.filter(
    (rule) => rule.source === bracketSlot && rule.sourceResult === result,
  );
}
